#!/bin/sh

amixer -D default sset Channels 80%

CONFIGFILE=/root/.config/qtwebradio/WebRadio.conf
if [ -e ${CONFIGFILE} ]; then
    VOL=`cat ${CONFIGFILE} | grep "Volume="`
    if [ $VOL != "" ]; then
        VALUE=`echo ${VOL} | cut -d"=" -f2`
        #echo ${VALUE}
        amixer -D default sset Master ${VALUE}%
    fi
else
    echo "File \"${CONFIGFILE}\" not found"
    amixer -D default sset Master 60%
fi
