#!/bin/sh
#
# Start bluetoothd
#

start() {
	printf "Starting bluetoothd: "
	start-stop-daemon -b -S -q -m -p /var/run/bluetoothd.pid --exec /usr/libexec/bluetooth/bluetoothd
	echo "OK"
}

stop() {
	printf "Stopping bluetoothd: "
	start-stop-daemon -K -q -p /var/run/bluetoothd.pid
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
