#!/bin/sh
#
# Start bluealsa
#

start() {
	printf "Starting bluealsa: "
	start-stop-daemon -b -S -q -m -p /var/run/bluealsa.pid --exec /usr/bin/bluealsa
	echo "OK"
}

stop() {
	printf "Stopping bluealsa: "
	start-stop-daemon -K -q -p /var/run/bluealsa.pid
	echo "OK"
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	stop
	start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
